CREATE TABLE users (
    discord_id BIGINT PRIMARY KEY NOT NULL,
    global_name VARCHAR(32) NOT NULL,
    api_token VARCHAR(255) NOT NULL UNIQUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
